package apocalypse.fandomcraft.horror;

import apocalypse.fandomcraft.armour.JokePack;
import apocalypse.fandomcraft.blocks.BlockRock;
import apocalypse.fandomcraft.blocks.UnbreakableBlock;
import apocalypse.fandomcraft.blocks.compressedBlock;
import apocalypse.fandomcraft.fable.FableSword;
import apocalypse.fandomcraft.horror.entity.EntityBloodhound;
import apocalypse.fandomcraft.horror.entity.EntityCultist;
import apocalypse.fandomcraft.horror.entity.EntityFBI;
import apocalypse.fandomcraft.horror.entity.EntityFreddy;
import apocalypse.fandomcraft.horror.entity.EntityGreyChild;
import apocalypse.fandomcraft.horror.entity.EntityHeretic;
import apocalypse.fandomcraft.horror.entity.EntityJason;
import apocalypse.fandomcraft.horror.entity.EntityLGM;
import apocalypse.fandomcraft.horror.entity.EntityMerchantOther;
import apocalypse.fandomcraft.horror.entity.EntityMerchantOver;
import apocalypse.fandomcraft.horror.entity.EntityMummy;
import apocalypse.fandomcraft.horror.entity.EntityMyers;
import apocalypse.fandomcraft.horror.entity.EntityNurse;
import apocalypse.fandomcraft.horror.entity.EntityPoe;
import apocalypse.fandomcraft.horror.entity.EntityPyramid;
import apocalypse.fandomcraft.horror.entity.EntityStalker;
import apocalypse.fandomcraft.main.Main;
import apocalypse.fandomcraft.otherworld.OtherworldPortalBlock;
import apocalypse.fandomcraft.otherworld.OtherworldTrigger;
import apocalypse.fandomcraft.player.Backpack;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.BlockVine;
import net.minecraft.block.material.Material;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor.ArmorMaterial;

public class HorrorReg {
    public static final Enchantment lightfoot = new EnchantmentLightfoot(100, 6);
    public static Item record;
    public static Item record_halloween;
    public static Item record_xfiles;
    public static Item record_siren;
    public static Item record_pyramid;
    public static Item record_omen;
    public static Block otherworldPortal;
    public static Item haloOfTheSun;
    public static Block bloodGrass;
    public static Block bloodstoneRock;
    public static Block gravitite;
    public static Block bloodleaf;
    public static Block plant_thorns;
    public static Block plant_grass;
    public static Block plant_trap;
    public static Block otherworldBlock;
    public static Block bloodBlock;
    public static Block bloodstoneOre;
    public static Block flowervine;
    public static Block otherworldBlock2;
    public static Block rusty_iron_bars;
    public static Block otherworldBlockBreakable;
    public static Block otherworldBlockBreakable2;
    public static Block rusty_iron_barsBreakable;
    public static Item gravititeDust;
    public static Item machette;
    public static Item bladedGlove;
    public static Item pumpkinBomb;
    public static Item throwingKnife;
    public static Item chainsaw;
    public static Item smallPumpkin;
    public static Item shadowleaf;
    public static Item handgun;
    public static Item giantKnife;
    public static Item jetpack;
    public static Item jokepack;
    public static Item fuelCanister;
    public static Item gravityRod;
    public static Item rustClump;
    public static Item backpack;
    public static Item maskJason;
    public static Item maskMyers;
    public static Item holyWater;
    public static Block trash_bin;

    public HorrorReg() {
    }

    public static void register() {
        record = (new Item()).setUnlocalizedName("record").setCreativeTab(Main.tabFandomCraftMusic).setTextureName("fandomcraft:record");
        GameRegistry.registerItem(record, "record");
        record_halloween = (new RecordHorror("Halloween")).setUnlocalizedName("record_halloween").setCreativeTab(Main.tabFandomCraftMusic).setTextureName("fandomcraft:record_bloody");
        GameRegistry.registerItem(record_halloween, "record_halloween");
        record_xfiles = (new RecordHorror("XFiles")).setUnlocalizedName("record_xfiles").setCreativeTab(Main.tabFandomCraftMusic).setTextureName("fandomcraft:record_bloody");
        GameRegistry.registerItem(record_xfiles, "record_xfiles");
        record_siren = (new RecordHorror("Siren")).setUnlocalizedName("record_siren").setCreativeTab(Main.tabFandomCraftMusic).setTextureName("fandomcraft:record_bloody");
        GameRegistry.registerItem(record_siren, "record_siren");
        record_pyramid = (new RecordHorror("Pyramid")).setUnlocalizedName("record_pyramid").setCreativeTab(Main.tabFandomCraftMusic).setTextureName("fandomcraft:record_bloody");
        GameRegistry.registerItem(record_pyramid, "record_pyramid");
        record_omen = (new RecordHorror("Omen")).setUnlocalizedName("record_omen").setCreativeTab(Main.tabFandomCraftMusic).setTextureName("fandomcraft:record_bloody");
        GameRegistry.registerItem(record_omen, "record_omen");
        otherworldPortal = (new OtherworldPortalBlock()).setBlockName("otherworldPortal").setBlockTextureName("fandomcraft:otherworldPortal");
        GameRegistry.registerBlock(otherworldPortal, "otherworldPortal");
        haloOfTheSun = (new OtherworldTrigger()).setUnlocalizedName("haloOfTheSun").setTextureName("fandomcraft:haloOfTheSun").setCreativeTab(Main.tabFandomCraftMisc);
        GameRegistry.registerItem(haloOfTheSun, "haloOfTheSun");
        bloodGrass = (new BloodGrass(Material.grass)).setBlockName("bloodGrass").setBlockTextureName("fandomcraft:bloodgrass").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(bloodGrass, "bloodGrass");
        bloodstoneRock = (new BlockRock(Material.rock)).setBlockName("bloodstoneRock").setBlockTextureName("fandomcraft:bloodstoneRock").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(bloodstoneRock, "bloodstoneRock");
        gravitite = (new Gravitite()).setBlockName("gravitite").setBlockTextureName("fandomcraft:gravititeOre").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(gravitite, "gravitite");
        gravititeDust = (new Item()).setUnlocalizedName("gravititeDust").setTextureName("fandomcraft:gravititeDust").setCreativeTab(Main.tabFandomCraftMisc);
        GameRegistry.registerItem(gravititeDust, "gravititeDust");
        machette = (new FableSword("", 400, 6.0F, true, 0)).setUnlocalizedName("machette").setTextureName("fandomcraft:machette").setCreativeTab(Main.tabFandomCraftWeapons);
        GameRegistry.registerItem(machette, "machette");
        bladedGlove = (new FableSword("", 400, 6.0F, true, 0)).setUnlocalizedName("bladedGlove").setTextureName("fandomcraft:bladedGlove").setCreativeTab(Main.tabFandomCraftWeapons);
        GameRegistry.registerItem(bladedGlove, "bladedGlove");
        chainsaw = (new FableSword("", 400, 6.0F, true, 0)).setUnlocalizedName("chainsaw").setTextureName("fandomcraft:chainsaw").setCreativeTab(Main.tabFandomCraftWeapons);
        GameRegistry.registerItem(chainsaw, "chainsaw");
        throwingKnife = (new ThrowingKnife()).setUnlocalizedName("throwingKnife").setTextureName("fandomcraft:throwingKnife").setCreativeTab(Main.tabFandomCraftWeapons);
        GameRegistry.registerItem(throwingKnife, "throwingKnife");
        jetpack = (new ItemJetpack(ArmorMaterial.IRON, 4, 1)).setUnlocalizedName("jetpack").setTextureName("fandomcraft:jetpack").setCreativeTab(Main.tabFandomCraftOutfits);
        GameRegistry.registerItem(jetpack, "jetpack");
        jokepack = (new JokePack(ArmorMaterial.IRON, 4, 1)).setUnlocalizedName("jokepack").setTextureName("fandomcraft:jetpack").setCreativeTab(Main.tabFandomCraftOutfits);
        GameRegistry.registerItem(jokepack, "jokepack");
        backpack = (new Backpack()).setUnlocalizedName("backpack").setTextureName("fandomcraft:backpack").setCreativeTab(Main.tabFandomCraftValuables);
        GameRegistry.registerItem(backpack, "backpack");
        bloodleaf = (new Bloodleaf(Material.leaves)).setBlockName("bloodleaf").setBlockTextureName("fandomcraft:bloodleaf").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(bloodleaf, "bloodleaf");
        maskJason = (new MaskJason(ArmorMaterial.IRON, 4, 0)).setUnlocalizedName("maskJason").setTextureName("fandomcraft:jasonMask").setCreativeTab(Main.tabFandomCraftOutfits);
        GameRegistry.registerItem(maskJason, "maskJason");
        maskMyers = (new MaskMyers(ArmorMaterial.IRON, 4, 0)).setUnlocalizedName("maskMyers").setTextureName("fandomcraft:maskMyers").setCreativeTab(Main.tabFandomCraftOutfits);
        GameRegistry.registerItem(maskMyers, "maskMyers");
        smallPumpkin = (new Item()).setUnlocalizedName("smallPumpkin").setTextureName("fandomcraft:smallPumpkin").setCreativeTab(Main.tabFandomCraftMisc);
        GameRegistry.registerItem(smallPumpkin, "smallPumpkin");
        pumpkinBomb = (new PumpkinBomb()).setUnlocalizedName("pumpkinBomb").setTextureName("fandomcraft:pumpkinBomb").setCreativeTab(Main.tabFandomCraftWeapons);
        GameRegistry.registerItem(pumpkinBomb, "pumpkinBomb");
        holyWater = (new HolyWater()).setUnlocalizedName("holyWater").setTextureName("fandomcraft:holyWater").setCreativeTab(Main.tabFandomCraftMisc);
        GameRegistry.registerItem(holyWater, "holyWater");
        gravityRod = (new Item()).setUnlocalizedName("gravityRod").setTextureName("fandomcraft:shadowleaf").setCreativeTab(Main.tabFandomCraftMisc);
        GameRegistry.registerItem(gravityRod, "gravityRod");
        rustClump = (new Item()).setUnlocalizedName("rustClump").setTextureName("fandomcraft:rustClump").setCreativeTab(Main.tabFandomCraftMisc);
        GameRegistry.registerItem(rustClump, "rustClump");
        plant_thorns = (new PlantThorns(0.2F)).setBlockName("plant_thorns").setBlockTextureName("fandomcraft:plant_thorns").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(plant_thorns, "plant_thorns");
        plant_grass = (new HorrorPlant(0.3F)).setBlockName("plant_grass").setBlockTextureName("fandomcraft:plant_grass").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(plant_grass, "plant_grass");
        plant_trap = (new HorrorPlant(1.0F)).setBlockName("plant_trap").setBlockTextureName("fandomcraft:plant_trap").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(plant_trap, "plant_trap");
        flowervine = (new BlockVine()).setBlockName("flowervine").setBlockTextureName("fandomcraft:flowervine").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(flowervine, "flowervine");
        otherworldBlock = (new UnbreakableBlock(Material.iron)).setBlockName("otherworldBlock").setBlockTextureName("fandomcraft:otherworldBlock").setCreativeTab(Main.tabFandomCraftDungeons);
        GameRegistry.registerBlock(otherworldBlock, "otherworldBlock");
        otherworldBlock2 = (new UnbreakableBlock(Material.iron)).setBlockName("otherworldBlock2").setBlockTextureName("fandomcraft:otherworldBlock2").setCreativeTab(Main.tabFandomCraftDungeons);
        GameRegistry.registerBlock(otherworldBlock2, "otherworldBlock2");
        bloodBlock = (new BlockBlood()).setBlockName("bloodBlock").setBlockTextureName("fandomcraft:bloodBlock").setCreativeTab(Main.tabFandomCraftDungeons);
        GameRegistry.registerBlock(bloodBlock, "bloodBlock");
        bloodstoneOre = (new BloodstoneOre()).setBlockName("bloodstoneOre").setBlockTextureName("fandomcraft:bloodstoneOre").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(bloodstoneOre, "bloodstoneOre");
        rusty_iron_bars = (new NewPane("fandomcraft:rusty_iron_bars", "fandomcraft:rusty_iron_bars", Material.iron, true)).setBlockName("rusty_iron_bars").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(rusty_iron_bars, "rusty_iron_bars");
        otherworldBlockBreakable = (new compressedBlock()).setBlockName("otherworldBlockBreakable").setBlockTextureName("fandomcraft:otherworldBlock").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(otherworldBlockBreakable, "otherworldBlockBreakable");
        otherworldBlockBreakable2 = (new compressedBlock()).setBlockName("otherworldBlockBreakable2").setBlockTextureName("fandomcraft:otherworldBlock2").setCreativeTab(Main.tabFandomCraftBlocks);
        GameRegistry.registerBlock(otherworldBlockBreakable2, "otherworldBlockBreakable2");
        handgun = (new ItemHandgun()).setUnlocalizedName("handgun").setTextureName("fandomcraft:handgun").setCreativeTab(Main.tabFandomCraftWeapons);
        GameRegistry.registerItem(handgun, "handgun");
        giantKnife = (new FableSword("", 1000, 15.0F, true, 0)).setUnlocalizedName("giantKnife").setTextureName("fandomcraft:giantKnife").setCreativeTab(Main.tabFandomCraftWeapons);
        GameRegistry.registerItem(giantKnife, "giantKnife");
        trash_bin = (new TrashBin()).setBlockName("trash_bin").setCreativeTab(Main.tabFandomCraftModels);
        GameRegistry.registerBlock(trash_bin, "trash_bin");
    }

    public static void mobs() {
        EntityMerchantOver.mainRegistry();
        EntityMerchantOther.mainRegistry();
        EntityFBI.mainRegistry();
        EntityLGM.mainRegistry();
        EntityMummy.mainRegistry();
        EntityCultist.mainRegistry();
        EntityHeretic.mainRegistry();
        EntityPoe.mainRegistry();
        EntityJason.mainRegistry();
        EntityFreddy.mainRegistry();
        EntityMyers.mainRegistry();
        EntityBloodhound.mainRegistry();
        EntityGreyChild.mainRegistry();
        EntityStalker.mainRegistry();
        EntityNurse.mainRegistry();
        EntityPyramid.mainRegistry();
    }
}
