modLoader="javafml"

loaderVersion="[36,)"

license="All rights reserved"

issueTrackerURL="https://github.com/KingOfTheGamesYT/FandomCraft-Remix/issues"

[[mods]]
itemIcon="fandomcraft:cake_sword"

configBackground="fandomcraft:textures/blocks/adamantiumBlock"

modId="fandomcraft"

version="5.0.0"

displayName="FandomCraft"

displayURL="https://www.curseforge.com/minecraft/mc-mods/fandomcraft-remix"

logoFile="logo.png"

credits="LightAdept (packaging fix), Desfang (textures), zsora16x (textures), TmmCrafter (mob AI), coolAlias (backpack & overlay tutorials)"

authors="RedRoseWarrior aka DevMaster1015, Eria8, Ms_Raven (Miss_Apocalypse)"
description='''
Adds a thousand different items, blocks, mobs, dungeons and other features from many *fandoms* into one massive Minecraft mod."'''

# Base Forge
[[dependencies.fandomcraft]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

# Base Minecraft
[[dependencies.fandomcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

# Rises the limit for health, without it the mobs with above 512 health will have 512 health
[[dependencies.fandomcraft]]
modId="attributefix"
mandatory=false
versionRange="[10.1.2,)"
ordering="NONE"
side="BOTH"
