
modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/KingOfTheGamesYT/FandomCraft-Remix/issues" #optional
[[mods]] #mandatory
modId="fandomcraftremix" #mandatory
version="${file.jarVersion}" #mandatory
displayName="FandomCraft Remix" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/fandomcraft-remix" #optional
logoFile="examplemod.png" #optional
credits="LightAdept (packaging fix), Desfang (textures), zsora16x (textures), TmmCrafter (mob AI), coolAlias (backpack & overlay tutorials)" #optional
authors="Eria8, Ms_Raven (Miss_Apocalypse), Devmaster1015 aka RedRoseWarrior" #optional
description='''
Adds a thousand different items, blocks, mobs, dungeons and other features from many *fandoms* into one massive Minecraft mod.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
