// Date: 10/08/2014 19:13:35
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;

import apocalypse.fandomcraft.entity.EntityPikachu;

public class modelPikachu extends ModelBase
{
  //fields
    ModelRenderer RightEar;
    ModelRenderer LeftEar;
    ModelRenderer Head;
    ModelRenderer RightArm;
    ModelRenderer LeftArm;
    ModelRenderer Body;
    ModelRenderer RightLeg;
    ModelRenderer LeftLeg;
    ModelRenderer RightFoot;
    ModelRenderer LeftFoot;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Tail4;
    ModelRenderer Tail5;
    ModelRenderer Tail6;
  
  public modelPikachu()
  {
    textureWidth = 256;
    textureHeight = 64;
    
      RightEar = new ModelRenderer(this, 220, 0);
      RightEar.addBox(-2F, -14F, -2F, 4, 18, 5);
      RightEar.setRotationPoint(-7F, -20F, -1F);
      RightEar.setTextureSize(256, 64);
      RightEar.mirror = true;
      setRotation(RightEar, -0.2617994F, 0F, -0.2617994F);
      LeftEar = new ModelRenderer(this, 238, 0);
      LeftEar.addBox(-2F, -14F, -2F, 4, 18, 5);
      LeftEar.setRotationPoint(9F, -18F, -1F);
      LeftEar.setTextureSize(256, 64);
      LeftEar.mirror = true;
      setRotation(LeftEar, -0.2617994F, 0F, 0.9599311F);
      Head = new ModelRenderer(this, 2, 28);
      Head.addBox(-9F, -18F, -9F, 18, 18, 18);
      Head.setRotationPoint(0F, 0F, -5F);
      Head.setTextureSize(256, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      RightArm = new ModelRenderer(this, 0, 33);
      RightArm.addBox(-5F, 0F, -2.5F, 5, 8, 5);
      RightArm.setRotationPoint(-5F, 2F, -7F);
      RightArm.setTextureSize(256, 64);
      RightArm.mirror = true;
      setRotation(RightArm, -0.2443461F, 0F, -0.3490659F);
      LeftArm = new ModelRenderer(this, 56, 33);
      LeftArm.addBox(0F, 0F, -2.5F, 5, 8, 5);
      LeftArm.setRotationPoint(5F, 2F, -7F);
      LeftArm.setTextureSize(256, 64);
      LeftArm.mirror = true;
      setRotation(LeftArm, -0.2443461F, 0F, 0.3490659F);
      Body = new ModelRenderer(this, 196, 28);
      Body.addBox(-8F, -12F, -7F, 16, 22, 14);
      Body.setRotationPoint(0F, 10F, 1F);
      Body.setTextureSize(256, 64);
      Body.mirror = true;
      setRotation(Body, 0.2443461F, 0F, 0F);
      RightLeg = new ModelRenderer(this, 74, 45);
      RightLeg.addBox(-4F, 0F, -6F, 8, 9, 10);
      RightLeg.setRotationPoint(5F, 13F, 0F);
      RightLeg.setTextureSize(256, 64);
      RightLeg.mirror = true;
      setRotation(RightLeg, 0.2094395F, 0F, 0F);
      LeftLeg = new ModelRenderer(this, 110, 45);
      LeftLeg.addBox(-4F, 0F, -6F, 8, 9, 10);
      LeftLeg.setRotationPoint(-5F, 13F, 0F);
      LeftLeg.setTextureSize(256, 64);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, 0.2094395F, 0F, 0F);
      RightFoot = new ModelRenderer(this, 0, 0);
      RightFoot.addBox(-3F, 0F, -5F, 6, 3, 8);
      RightFoot.setRotationPoint(5F, 21F, -1F);
      RightFoot.setTextureSize(256, 64);
      RightFoot.mirror = true;
      setRotation(RightFoot, 0F, 0F, 0F);
      LeftFoot = new ModelRenderer(this, 0, 11);
      LeftFoot.addBox(-3F, 0F, -5F, 6, 3, 8);
      LeftFoot.setRotationPoint(-5F, 21F, -1F);
      LeftFoot.setTextureSize(256, 64);
      LeftFoot.mirror = true;
      setRotation(LeftFoot, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 26, 0);
      Tail1.addBox(0F, -1F, 0F, 1, 4, 13);
      Tail1.setRotationPoint(0F, 13F, 7F);
      Tail1.setTextureSize(256, 64);
      Tail1.mirror = true;
      setRotation(Tail1, 0.5235988F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 41, 2);
      Tail2.addBox(0F, 0F, 0F, 1, 7, 4);
      Tail2.setRotationPoint(0F, 2F, 11F);
      Tail2.setTextureSize(256, 64);
      Tail2.mirror = true;
      setRotation(Tail2, 0.5235988F, 0F, 0F);
      Tail3 = new ModelRenderer(this, 54, 0);
      Tail3.addBox(0F, 0F, 0F, 1, 5, 12);
      Tail3.setRotationPoint(0F, 1F, 10F);
      Tail3.setTextureSize(256, 64);
      Tail3.mirror = true;
      setRotation(Tail3, 0.6806784F, 0F, 0F);
      Tail4 = new ModelRenderer(this, 80, 0);
      Tail4.addBox(0F, 0F, 0F, 1, 9, 5);
      Tail4.setRotationPoint(0F, -10F, 10F);
      Tail4.setTextureSize(256, 64);
      Tail4.mirror = true;
      setRotation(Tail4, 0.6981317F, 0F, 0F);
      Tail5 = new ModelRenderer(this, 92, 0);
      Tail5.addBox(0F, 0F, 0F, 1, 5, 17);
      Tail5.setRotationPoint(0F, -11F, 10F);
      Tail5.setTextureSize(256, 64);
      Tail5.mirror = true;
      setRotation(Tail5, 0.5235988F, 0F, 0F);
      Tail6 = new ModelRenderer(this, 92, 0);
      Tail6.addBox(0F, -2F, 0F, 1, 5, 17);
      Tail6.setRotationPoint(0F, -9F, 11F);
      Tail6.setTextureSize(256, 64);
      Tail6.mirror = true;
      setRotation(Tail6, 0.8203047F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    RightEar.render(f5);
    LeftEar.render(f5);
    Head.render(f5);
    RightArm.render(f5);
    LeftArm.render(f5);
    Body.render(f5);
    RightLeg.render(f5);
    LeftLeg.render(f5);
    RightFoot.render(f5);
    LeftFoot.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Tail3.render(f5);
    Tail4.render(f5);
    Tail5.render(f5);
    Tail6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.Head.rotateAngleY = f3 / (180F / (float)Math.PI);
    this.Head.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.RightEar.rotateAngleX = this.Head.rotateAngleX;
    this.RightEar.rotateAngleY = this.Head.rotateAngleY;
    this.LeftEar.rotateAngleX = this.Head.rotateAngleX;
    this.LeftEar.rotateAngleY = this.Head.rotateAngleY;
    this.LeftLeg.rotateAngleX = -1.5F * this.func_78172_a(f, 13.0F) * f1;
    this.RightLeg.rotateAngleX = 1.5F * this.func_78172_a(f, 13.0F) * f1;
    this.LeftLeg.rotateAngleY = 0.0F;
    this.RightLeg.rotateAngleY = 0.0F;
    this.RightFoot.rotateAngleX = this.RightLeg.rotateAngleX;
    this.RightFoot.rotateAngleY = this.RightLeg.rotateAngleY;
    this.LeftFoot.rotateAngleX = this.LeftLeg.rotateAngleX;
    this.LeftFoot.rotateAngleY = this.LeftLeg.rotateAngleY;
  }
  public void setLivingAnimations(EntityLivingBase p_78086_1_, float p_78086_2_, float p_78086_3_, float p_78086_4_)
  {
      EntityPikachu chu = (EntityPikachu)p_78086_1_;
      int i = chu.getAttackTimer();

      if (i > 0)
      {
          this.RightArm.rotateAngleX = -2.0F + 1.5F * this.func_78172_a((float)i - p_78086_4_, 10.0F);
          this.LeftArm.rotateAngleX = -2.0F + 1.5F * this.func_78172_a((float)i - p_78086_4_, 10.0F);
      }
      else
      {
          this.RightArm.rotateAngleX = (-0.2F + 1.5F * this.func_78172_a(p_78086_2_, 13.0F)) * p_78086_3_;
          this.LeftArm.rotateAngleX = (-0.2F - 1.5F * this.func_78172_a(p_78086_2_, 13.0F)) * p_78086_3_;
      
      }
  }
  private float func_78172_a(float p_78172_1_, float p_78172_2_)
  {
      return (Math.abs(p_78172_1_ % p_78172_2_ - p_78172_2_ * 0.5F) - p_78172_2_ * 0.25F) / (p_78172_2_ * 0.25F);
  }

}
