// Date: 04/05/2014 16:26:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelCuttingBoard extends ModelBase
{
  //fields
    ModelRenderer board1;
    ModelRenderer board2;
    ModelRenderer handle;
    ModelRenderer blade;
  
  public modelCuttingBoard()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      board1 = new ModelRenderer(this, 0, 0);
      board1.addBox(0F, 0F, 0F, 9, 1, 10);
      board1.setRotationPoint(-4F, 23F, -7F);
      board1.setTextureSize(64, 32);
      board1.mirror = true;
      setRotation(board1, 0F, -0.3490659F, 0F);
      board2 = new ModelRenderer(this, 6, 11);
      board2.addBox(0F, 0F, 0F, 7, 1, 2);
      board2.setRotationPoint(-6.2F, 23F, 2F);
      board2.setTextureSize(64, 32);
      board2.mirror = true;
      setRotation(board2, 0F, -0.3490659F, 0F);
      handle = new ModelRenderer(this, 0, 11);
      handle.addBox(0F, 0F, 0F, 2, 1, 1);
      handle.setRotationPoint(6F, 23F, 5F);
      handle.setTextureSize(64, 32);
      handle.mirror = true;
      setRotation(handle, 0F, -1.22173F, 0F);
      blade = new ModelRenderer(this, 0, 0);
      blade.addBox(0F, -1F, 0F, 4, 0, 1);
      blade.setRotationPoint(4.9F, 24.5F, 1.2F);
      blade.setTextureSize(64, 32);
      blade.mirror = true;
      setRotation(blade, 0F, -1.22173F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    board1.render(f5);
    board2.render(f5);
    handle.render(f5);
    blade.render(f5);
  }
  
  public void renderModel(float f)
  {

	    board1.render(f);
	    board2.render(f);
	    handle.render(f);
	    blade.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
