// Date: 03/05/2014 00:07:23
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelPC extends ModelBase
{
  //fields
    ModelRenderer keyboard;
    ModelRenderer monitor;
    ModelRenderer mouse;
    ModelRenderer tower;
    ModelRenderer neck;
    ModelRenderer neckstand;
    ModelRenderer neckpiece;
  
  public modelPC()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      keyboard = new ModelRenderer(this, 0, 52);
      keyboard.addBox(0F, 0F, 0F, 29, 1, 11);
      keyboard.setRotationPoint(-14F, 53F, -14F);
      keyboard.setTextureSize(128, 64);
      keyboard.mirror = true;
      setRotation(keyboard, 0F, -0.3346075F, 0F);
      monitor = new ModelRenderer(this, 6, 25);
      monitor.addBox(0F, 0F, 0F, 36, 25, 2);
      monitor.setRotationPoint(-18F, 17F, 8F);
      monitor.setTextureSize(128, 64);
      monitor.mirror = true;
      setRotation(monitor, 0F, 0F, 0F);
      mouse = new ModelRenderer(this, 69, 56);
      mouse.addBox(0F, -1F, 0F, 3, 2, 5);
      mouse.setRotationPoint(14F, 53F, -13F);
      mouse.setTextureSize(128, 64);
      mouse.mirror = true;
      setRotation(mouse, 0F, -0.2974289F, 0F);
      tower = new ModelRenderer(this, 6, 8);
      tower.addBox(0F, 0F, 0F, 24, 7, 10);
      tower.setRotationPoint(-12F, 47F, 6F);
      tower.setTextureSize(128, 64);
      tower.mirror = true;
      setRotation(tower, 0F, 0F, 0F);
      neck = new ModelRenderer(this, 0, 31);
      neck.addBox(0F, 0F, 0F, 2, 20, 1);
      neck.setRotationPoint(-1F, 27F, 10F);
      neck.setTextureSize(128, 64);
      neck.mirror = true;
      setRotation(neck, 0.1115358F, 0F, 0F);
      neckstand = new ModelRenderer(this, 10, 0);
      neckstand.addBox(0F, 0F, 0F, 12, 1, 6);
      neckstand.setRotationPoint(-6F, 46F, 9F);
      neckstand.setTextureSize(128, 64);
      neckstand.mirror = true;
      setRotation(neckstand, 0F, 0F, 0F);
      neckpiece = new ModelRenderer(this, 0, 0);
      neckpiece.addBox(0F, 0F, 0F, 4, 6, 1);
      neckpiece.setRotationPoint(-2F, 25F, 10F);
      neckpiece.setTextureSize(128, 64);
      neckpiece.mirror = true;
      setRotation(neckpiece, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    keyboard.render(f5);
    monitor.render(f5);
    mouse.render(f5);
    tower.render(f5);
    neck.render(f5);
    neckstand.render(f5);
    neckpiece.render(f5);
  }
  public void renderModel(float f)
  {
	    keyboard.render(f);
	    monitor.render(f);
	    mouse.render(f);
	    tower.render(f);
	    neck.render(f);
	    neckstand.render(f);
	    neckpiece.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
