// Date: 10/08/2014 19:14:32
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelShell extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Base2;
    ModelRenderer Base3;
    ModelRenderer Base4;
    ModelRenderer Edge1;
    ModelRenderer Edge2;
  
  public modelShell()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 80, 16);
      Base.addBox(-5F, -2F, -7F, 10, 4, 14);
      Base.setRotationPoint(0F, 21F, 0F);
      Base.setTextureSize(128, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Base2 = new ModelRenderer(this, 84, 34);
      Base2.addBox(-6F, -2F, -5F, 12, 4, 10);
      Base2.setRotationPoint(0F, 21F, 0F);
      Base2.setTextureSize(128, 64);
      Base2.mirror = true;
      setRotation(Base2, 0F, 0F, 0F);
      Base3 = new ModelRenderer(this, 0, 16);
      Base3.addBox(-4F, -1F, -5F, 8, 7, 10);
      Base3.setRotationPoint(0F, 18F, 0F);
      Base3.setTextureSize(128, 64);
      Base3.mirror = true;
      setRotation(Base3, 0F, 0F, 0F);
      Base4 = new ModelRenderer(this, 0, 0);
      Base4.addBox(-5F, -2F, -6F, 10, 4, 12);
      Base4.setRotationPoint(0F, 20F, 0F);
      Base4.setTextureSize(128, 64);
      Base4.mirror = true;
      setRotation(Base4, 0F, 0F, 0F);
      Edge1 = new ModelRenderer(this, 76, 0);
      Edge1.addBox(-5.5F, -0.5F, -7.5F, 11, 1, 15);
      Edge1.setRotationPoint(0F, 22F, 0F);
      Edge1.setTextureSize(128, 64);
      Edge1.mirror = true;
      setRotation(Edge1, 0F, 0F, 0F);
      Edge2 = new ModelRenderer(this, 77, 3);
      Edge2.addBox(-6.5F, -0.5F, -6F, 13, 1, 12);
      Edge2.setRotationPoint(0F, 22F, 0F);
      Edge2.setTextureSize(128, 64);
      Edge2.mirror = true;
      setRotation(Edge2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Base2.render(f5);
    Base3.render(f5);
    Base4.render(f5);
    Edge1.render(f5);
    Edge2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
