// Date: 06/08/2014 21:13:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelPikoHammer extends ModelBase
{
  //fields
    ModelRenderer Handle;
    ModelRenderer Base0;
    ModelRenderer Base1;
  
  public modelPikoHammer()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Handle = new ModelRenderer(this, 0, 0);
      Handle.addBox(0F, 0F, 0F, 1, 18, 1);
      Handle.setRotationPoint(0F, 0F, 0F);
      Handle.setTextureSize(64, 64);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0F);
      Base0 = new ModelRenderer(this, 5, 19);
      Base0.addBox(0F, 0F, 0F, 7, 7, 11);
      Base0.setRotationPoint(-3F, -6F, -5F);
      Base0.setTextureSize(64, 64);
      Base0.mirror = true;
      setRotation(Base0, 0F, 0F, 0F);
      Base1 = new ModelRenderer(this, 4, 0);
      Base1.addBox(0F, 0F, 0F, 7, 7, 12);
      Base1.setRotationPoint(-4.5F, -2.5F, -5.5F);
      Base1.setTextureSize(64, 64);
      Base1.mirror = true;
      setRotation(Base1, 0F, 0F, -0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Handle.render(f5);
    Base0.render(f5);
    Base1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
