// Date: 06/08/2014 23:01:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelChao extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Headwear;
    ModelRenderer Body;
    ModelRenderer RightArm;
    ModelRenderer LeftArm;
    ModelRenderer RightLeg;
    ModelRenderer LeftLeg;
  
  public modelChao()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(1F, -1F, -2F, 3, 3, 3);
      Head.setRotationPoint(0F, -19F, -3F);
      Head.setTextureSize(64, 64);
      Head.mirror = true;
      setRotation(Head, 0.7504916F, -1.570796F, -0.8028515F);
      Headwear = new ModelRenderer(this, 0, 16);
      Headwear.addBox(-4F, -8F, -4F, 8, 8, 8);
      Headwear.setRotationPoint(0F, -8F, -1F);
      Headwear.setTextureSize(64, 64);
      Headwear.mirror = true;
      setRotation(Headwear, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 32, 16);
      Body.addBox(-4F, 0F, -2F, 6, 6, 5);
      Body.setRotationPoint(1F, -8F, -1F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      RightArm = new ModelRenderer(this, 56, 0);
      RightArm.addBox(-1F, -2F, -1F, 2, 9, 2);
      RightArm.setRotationPoint(-4F, -6F, 0F);
      RightArm.setTextureSize(64, 64);
      setRotation(RightArm, 0F, 0F, 0.2268928F);
      LeftArm = new ModelRenderer(this, 56, 0);
      LeftArm.addBox(-1F, -2F, -1F, 2, 9, 2);
      LeftArm.setRotationPoint(4F, -6F, 0F);
      LeftArm.setTextureSize(64, 64);
      setRotation(LeftArm, 0F, 0F, -0.2268928F);
      LeftArm.mirror = false;
      RightLeg = new ModelRenderer(this, 48, 0);
      RightLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      RightLeg.setRotationPoint(-2F, -2F, -1F);
      RightLeg.setTextureSize(64, 64);
      RightLeg.mirror = false;
      setRotation(RightLeg, -0.4363323F, 0.2617994F, 0F);
      LeftLeg = new ModelRenderer(this, 48, 0);
      LeftLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      LeftLeg.setRotationPoint(2F, -2F, -1F);
      LeftLeg.setTextureSize(64, 64);
      setRotation(LeftLeg, -0.4363323F, -0.2617994F, 0F);
      LeftLeg.mirror = false;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Head.render(f5);
    Headwear.render(f5);
    Body.render(f5);
    RightArm.render(f5);
    LeftArm.render(f5);
    RightLeg.render(f5);
    LeftLeg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;

  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    float f6 = (180F / (float)Math.PI);
    this.Headwear.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.Headwear.rotateAngleY = f3 / (180F / (float)Math.PI);

  }

}
