// Date: 20/08/2014 18:38:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelArmos extends ModelBase
{
  //fields
    ModelRenderer Totem;
    ModelRenderer FanL;
    ModelRenderer FanM;
    ModelRenderer FanR;
    ModelRenderer Soul;
    ModelRenderer Armour;
    ModelRenderer Mouth;
    ModelRenderer Jaw;
    ModelRenderer Shoulder;
    ModelRenderer HeadTop;
    ModelRenderer RightArm;
    ModelRenderer LeftArm;
    ModelRenderer RightHand;
    ModelRenderer LeftHand;
    ModelRenderer LeftGlove;
    ModelRenderer RightGlove;
    ModelRenderer Handle1;
    ModelRenderer Handle2;
    ModelRenderer Handle3;
    ModelRenderer Hammer1;
    ModelRenderer Hammer2;
    ModelRenderer ShieldB;
    ModelRenderer ShieldM;
    ModelRenderer ShieldT;
  
  public modelArmos()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Totem = new ModelRenderer(this, 0, 0);
      Totem.addBox(-7.5F, -16F, -2F, 15, 40, 14);
      Totem.setRotationPoint(0F, 0F, 4F);
      Totem.setTextureSize(256, 128);
      Totem.mirror = true;
      setRotation(Totem, -0.122173F, 0F, 0F);
      FanL = new ModelRenderer(this, 56, 0);
      FanL.addBox(-9F, -18F, 0F, 9, 18, 1);
      FanL.setRotationPoint(-6F, -6F, -5F);
      FanL.setTextureSize(256, 128);
      FanL.mirror = true;
      setRotation(FanL, 0F, 0.418879F, 0F);
      FanM = new ModelRenderer(this, 56, 33);
      FanM.addBox(-6F, -18F, 0F, 12, 20, 1);
      FanM.setRotationPoint(0F, -6F, -5F);
      FanM.setTextureSize(256, 128);
      FanM.mirror = true;
      setRotation(FanM, 0F, 0F, 0F);
      FanR = new ModelRenderer(this, 82, 35);
      FanR.addBox(0F, -18F, 0F, 9, 18, 1);
      FanR.setRotationPoint(6F, -6F, -5F);
      FanR.setTextureSize(256, 128);
      FanR.mirror = true;
      setRotation(FanR, 0F, -0.418879F, 0F);
      Soul = new ModelRenderer(this, 76, 0);
      Soul.addBox(-7F, -16F, 0F, 14, 15, 11);
      Soul.setRotationPoint(0F, 13F, -8F);
      Soul.setTextureSize(256, 128);
      Soul.mirror = true;
      setRotation(Soul, -0.122173F, 0F, 0F);
      Armour = new ModelRenderer(this, 0, 54);
      Armour.addBox(-9F, -5F, 0F, 18, 20, 14);
      Armour.setRotationPoint(0F, 0F, -7F);
      Armour.setTextureSize(256, 128);
      Armour.mirror = true;
      setRotation(Armour, -0.122173F, 0F, 0F);
      Mouth = new ModelRenderer(this, 0, 88);
      Mouth.addBox(-10F, 0F, 0F, 20, 12, 7);
      Mouth.setRotationPoint(0F, 4F, -8.5F);
      Mouth.setTextureSize(256, 128);
      Mouth.mirror = true;
      setRotation(Mouth, -0.0698132F, 0F, 0F);
      Jaw = new ModelRenderer(this, 0, 107);
      Jaw.addBox(-11F, 0F, 0F, 22, 5, 16);
      Jaw.setRotationPoint(0F, 14F, -10F);
      Jaw.setTextureSize(256, 128);
      Jaw.mirror = true;
      setRotation(Jaw, -0.0698132F, 0F, 0F);
      Shoulder = new ModelRenderer(this, 76, 113);
      Shoulder.addBox(-12F, 0F, 0F, 24, 7, 8);
      Shoulder.setRotationPoint(0F, -2F, 6F);
      Shoulder.setTextureSize(256, 128);
      Shoulder.mirror = true;
      setRotation(Shoulder, 0F, 0F, 0F);
      HeadTop = new ModelRenderer(this, 126, 0);
      HeadTop.addBox(-4F, -12F, -4F, 8, 12, 8);
      HeadTop.setRotationPoint(0F, 0F, 0F);
      HeadTop.setTextureSize(256, 128);
      HeadTop.mirror = true;
      setRotation(HeadTop, -0.6283185F, 0F, 0F);
      RightArm = new ModelRenderer(this, 54, 95);
      RightArm.addBox(0F, -3F, -3F, 16, 6, 6);
      RightArm.setRotationPoint(10F, 2F, 10F);
      RightArm.setTextureSize(256, 128);
      RightArm.mirror = true;
      setRotation(RightArm, 0F, 0.4363323F, 0.8726646F);
      LeftArm = new ModelRenderer(this, 54, 95);
      LeftArm.addBox(-16F, -3F, -3F, 16, 6, 6);
      LeftArm.setRotationPoint(-10F, 2F, 10F);
      LeftArm.setTextureSize(256, 128);
      LeftArm.mirror = true;
      setRotation(LeftArm, 0F, -0.4363323F, -0.8726646F);
      RightHand = new ModelRenderer(this, 54, 95);
      RightHand.addBox(0F, -3F, -3F, 16, 6, 6);
      RightHand.setRotationPoint(19F, 13F, 6F);
      RightHand.setTextureSize(256, 128);
      RightHand.mirror = true;
      setRotation(RightHand, 0F, 1.308997F, 0.2617994F);
      LeftHand = new ModelRenderer(this, 54, 95);
      LeftHand.addBox(-16F, -3F, -3F, 16, 6, 6);
      LeftHand.setRotationPoint(-19F, 13F, 6F);
      LeftHand.setTextureSize(256, 128);
      LeftHand.mirror = true;
      setRotation(LeftHand, 0F, -1.308997F, -0.2617994F);
      LeftGlove = new ModelRenderer(this, 98, 97);
      LeftGlove.addBox(-4F, -4F, -8F, 8, 8, 8);
      LeftGlove.setRotationPoint(-23F, 17F, -8F);
      LeftGlove.setTextureSize(256, 128);
      LeftGlove.mirror = true;
      setRotation(LeftGlove, 0.122173F, 0F, 0F);
      RightGlove = new ModelRenderer(this, 98, 97);
      RightGlove.addBox(-4F, -4F, -8F, 8, 8, 8);
      RightGlove.setRotationPoint(23F, 17F, -8F);
      RightGlove.setTextureSize(256, 128);
      RightGlove.mirror = true;
      setRotation(RightGlove, 0.122173F, 0F, 0F);
      Handle1 = new ModelRenderer(this, 64, 54);
      Handle1.addBox(0F, 0F, 0F, 3, 21, 3);
      Handle1.setRotationPoint(-23.5F, 3F, -16F);
      Handle1.setTextureSize(256, 128);
      Handle1.mirror = true;
      setRotation(Handle1, 0.122173F, 0F, 0F);
      Handle2 = new ModelRenderer(this, 64, 54);
      Handle2.addBox(0F, 0F, 0F, 3, 7, 3);
      Handle2.setRotationPoint(-23.5F, -0.2F, -20F);
      Handle2.setTextureSize(256, 128);
      Handle2.mirror = true;
      setRotation(Handle2, 0.7853982F, 0F, 0F);
      Handle3 = new ModelRenderer(this, 64, 54);
      Handle3.addBox(0F, 0F, 0F, 3, 27, 5);
      Handle3.setRotationPoint(-23.5F, -27.1F, -18F);
      Handle3.setTextureSize(256, 128);
      Handle3.mirror = true;
      setRotation(Handle3, -0.0872665F, 0F, 0F);
      Hammer1 = new ModelRenderer(this, 128, 54);
      Hammer1.addBox(-7F, -7F, -9F, 14, 14, 20);
      Hammer1.setRotationPoint(-22F, -14F, -23F);
      Hammer1.setTextureSize(256, 128);
      Hammer1.mirror = true;
      setRotation(Hammer1, 0.122173F, 0F, 0F);
      Hammer2 = new ModelRenderer(this, 80, 54);
      Hammer2.addBox(-8F, -7F, -9F, 16, 18, 8);
      Hammer2.setRotationPoint(-22F, -15F, -25F);
      Hammer2.setTextureSize(256, 128);
      Hammer2.mirror = true;
      setRotation(Hammer2, 0.0698132F, 0F, 0F);
      ShieldB = new ModelRenderer(this, 200, 80);
      ShieldB.addBox(0F, 0F, 0F, 3, 10, 25);
      ShieldB.setRotationPoint(26F, 13F, -22F);
      ShieldB.setTextureSize(256, 128);
      ShieldB.mirror = true;
      setRotation(ShieldB, 0F, 0F, 0.1745329F);
      ShieldM = new ModelRenderer(this, 200, 35);
      ShieldM.addBox(0F, 0F, 0F, 3, 20, 25);
      ShieldM.setRotationPoint(26F, -6F, -22F);
      ShieldM.setTextureSize(256, 128);
      ShieldM.mirror = true;
      setRotation(ShieldM, 0F, 0F, 0F);
      ShieldT = new ModelRenderer(this, 200, 0);
      ShieldT.addBox(-3F, 0F, 0F, 3, 10, 25);
      ShieldT.setRotationPoint(27.3F, -16F, -22F);
      ShieldT.setTextureSize(256, 128);
      ShieldT.mirror = true;
      setRotation(ShieldT, 0F, 0F, -0.1745329F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Totem.render(f5);
    FanL.render(f5);
    FanM.render(f5);
    FanR.render(f5);
    Soul.render(f5);
    Armour.render(f5);
    Mouth.render(f5);
    Jaw.render(f5);
    Shoulder.render(f5);
    HeadTop.render(f5);
    RightArm.render(f5);
    LeftArm.render(f5);
    RightHand.render(f5);
    LeftHand.render(f5);
    LeftGlove.render(f5);
    RightGlove.render(f5);
    Handle1.render(f5);
    Handle2.render(f5);
    Handle3.render(f5);
    Hammer1.render(f5);
    Hammer2.render(f5);
    ShieldB.render(f5);
    ShieldM.render(f5);
    ShieldT.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
