// Date: 09/08/2014 10:00:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelGoomba extends ModelBase
{
  //fields
    ModelRenderer RightLeg;
    ModelRenderer LeftLeg;
    ModelRenderer Body;
    ModelRenderer HeadBase;
    ModelRenderer HeadTop;
    ModelRenderer EyebrowLeft;
    ModelRenderer EyebrowRight;
    ModelRenderer ToothRight;
    ModelRenderer ToothLeft;
  
  public modelGoomba()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      RightLeg = new ModelRenderer(this, 3, 25);
      RightLeg.addBox(-2F, 0F, -3F, 4, 2, 5);
      RightLeg.setRotationPoint(-3F, 22F, 0F);
      RightLeg.setTextureSize(64, 32);
      RightLeg.mirror = true;
      setRotation(RightLeg, 0F, 0.1745329F, 0F);
      LeftLeg = new ModelRenderer(this, 3, 25);
      LeftLeg.addBox(-2F, 0F, -3F, 4, 2, 5);
      LeftLeg.setRotationPoint(3F, 22F, 0F);
      LeftLeg.setTextureSize(64, 32);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, 0F, -0.1745329F, 0F);
      Body = new ModelRenderer(this, 0, 16);
      Body.addBox(-3F, 0F, -3F, 6, 3, 6);
      Body.setRotationPoint(0F, 19F, 1F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      HeadBase = new ModelRenderer(this, 24, 18);
      HeadBase.addBox(-5F, 0F, -5F, 10, 4, 10);
      HeadBase.setRotationPoint(0F, 16F, 1F);
      HeadBase.setTextureSize(64, 32);
      HeadBase.mirror = true;
      setRotation(HeadBase, 0F, 0F, 0F);
      HeadTop = new ModelRenderer(this, 28, 5);
      HeadTop.addBox(-4F, 0F, -4F, 8, 5, 8);
      HeadTop.setRotationPoint(0F, 11F, 1F);
      HeadTop.setTextureSize(64, 32);
      HeadTop.mirror = true;
      setRotation(HeadTop, 0F, 0F, 0F);
      EyebrowLeft = new ModelRenderer(this, 0, 0);
      EyebrowLeft.addBox(-2F, 0F, 0F, 5, 1, 1);
      EyebrowLeft.setRotationPoint(2F, 12F, -4F);
      EyebrowLeft.setTextureSize(64, 32);
      EyebrowLeft.mirror = true;
      setRotation(EyebrowLeft, 0F, 0F, -0.4363323F);
      EyebrowRight = new ModelRenderer(this, 0, 0);
      EyebrowRight.addBox(-3F, 0F, 0F, 5, 1, 1);
      EyebrowRight.setRotationPoint(-2F, 12F, -4F);
      EyebrowRight.setTextureSize(64, 32);
      EyebrowRight.mirror = true;
      setRotation(EyebrowRight, 0F, 0F, 0.4363323F);
      ToothRight = new ModelRenderer(this, 0, 2);
      ToothRight.addBox(0F, -1F, 0F, 1, 2, 1);
      ToothRight.setRotationPoint(-4F, 17F, -4.5F);
      ToothRight.setTextureSize(64, 32);
      ToothRight.mirror = true;
      setRotation(ToothRight, 0.3490659F, 0F, -0.2443461F);
      ToothLeft = new ModelRenderer(this, 0, 2);
      ToothLeft.addBox(0F, -1F, 0F, 1, 2, 1);
      ToothLeft.setRotationPoint(3F, 17F, -4.5F);
      ToothLeft.setTextureSize(64, 32);
      ToothLeft.mirror = true;
      setRotation(ToothLeft, 0.3490659F, 0F, 0.2443461F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    RightLeg.render(f5);
    LeftLeg.render(f5);
    Body.render(f5);
    HeadBase.render(f5);
    HeadTop.render(f5);
    EyebrowLeft.render(f5);
    EyebrowRight.render(f5);
    ToothRight.render(f5);
    ToothLeft.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
