// Date: 26/08/2014 19:01:43
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelMew extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Nose;
    ModelRenderer LeftEar;
    ModelRenderer RightEar;
    ModelRenderer Body;
    ModelRenderer Butt;
    ModelRenderer Neck;
    ModelRenderer RightLeg;
    ModelRenderer LeftLeg;
    ModelRenderer RightArm;
    ModelRenderer LeftArm;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer RightFoot;
    ModelRenderer LeftFoot;
  
  public modelMew()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(-4F, -7F, -3F, 8, 7, 6);
      Head.setRotationPoint(0F, 0F, 0F);
      Head.setTextureSize(64, 128);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Nose = new ModelRenderer(this, 12, 13);
      Nose.addBox(-2F, -1F, -2F, 4, 2, 2);
      Nose.setRotationPoint(0F, -0.5F, -1.5F);
      Nose.setTextureSize(64, 128);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
      LeftEar = new ModelRenderer(this, 0, 13);
      LeftEar.addBox(-2F, -3F, 0F, 4, 4, 2);
      LeftEar.setRotationPoint(2.5F, -5.5F, 0F);
      LeftEar.setTextureSize(64, 128);
      LeftEar.mirror = true;
      setRotation(LeftEar, 0F, 0.2268928F, 0.7853982F);
      RightEar = new ModelRenderer(this, 0, 13);
      RightEar.addBox(-4F, -2F, 0F, 4, 4, 2);
      RightEar.setRotationPoint(-2F, -5F, 0F);
      RightEar.setTextureSize(64, 128);
      RightEar.mirror = true;
      setRotation(RightEar, 0F, -0.2268928F, 0.7853982F);
      Body = new ModelRenderer(this, 28, 0);
      Body.addBox(-2.5F, 0F, -2F, 5, 10, 4);
      Body.setRotationPoint(0F, 1F, 1F);
      Body.setTextureSize(64, 128);
      Body.mirror = true;
      setRotation(Body, 0.122173F, 0F, 0F);
      Butt = new ModelRenderer(this, 0, 19);
      Butt.addBox(-3F, 0F, -2.5F, 6, 6, 5);
      Butt.setRotationPoint(0F, 5F, 1.4F);
      Butt.setTextureSize(64, 128);
      Butt.mirror = true;
      setRotation(Butt, 0.1745329F, 0F, 0F);
      Neck = new ModelRenderer(this, 46, 0);
      Neck.addBox(-2F, -1F, -1.5F, 4, 3, 3);
      Neck.setRotationPoint(0F, 0F, 1F);
      Neck.setTextureSize(64, 128);
      Neck.mirror = true;
      setRotation(Neck, 0.122173F, 0F, 0F);
      RightLeg = new ModelRenderer(this, 36, 14);
      RightLeg.addBox(-2F, 0F, -2F, 3, 4, 4);
      RightLeg.setRotationPoint(-1.5F, 8F, 0.5F);
      RightLeg.setTextureSize(64, 128);
      RightLeg.mirror = true;
      setRotation(RightLeg, 0.2094395F, 0F, 0F);
      LeftLeg = new ModelRenderer(this, 36, 14);
      LeftLeg.addBox(-1F, 0F, -2F, 3, 4, 4);
      LeftLeg.setRotationPoint(1.5F, 8F, 0.5F);
      LeftLeg.setTextureSize(64, 128);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, 0.2094395F, 0F, 0F);
      RightArm = new ModelRenderer(this, 0, 30);
      RightArm.addBox(-2F, 0F, -1F, 2, 5, 2);
      RightArm.setRotationPoint(-2F, 2F, 0F);
      RightArm.setTextureSize(64, 128);
      RightArm.mirror = true;
      setRotation(RightArm, -0.3316126F, 0F, 0.2443461F);
      LeftArm = new ModelRenderer(this, 0, 30);
      LeftArm.addBox(0F, 0F, -1F, 2, 5, 2);
      LeftArm.setRotationPoint(2F, 2F, 0F);
      LeftArm.setTextureSize(64, 128);
      LeftArm.mirror = true;
      setRotation(RightArm, -0.3316126F, 0F, -0.2443461F);
      Tail1 = new ModelRenderer(this, 22, 14);
      Tail1.addBox(-0.5F, 0F, 0F, 1, 1, 12);
      Tail1.setRotationPoint(0F, 9F, 3F);
      Tail1.setTextureSize(64, 128);
      Tail1.mirror = true;
      setRotation(Tail1, 0.715585F, -0.9948377F, 0F);
      Tail2 = new ModelRenderer(this, 16, 14);
      Tail2.addBox(-0.5F, -0.5F, 0F, 1, 1, 18);
      Tail2.setRotationPoint(-8F, 1.5F, 8F);
      Tail2.setTextureSize(64, 128);
      Tail2.mirror = true;
      setRotation(Tail2, 2.565634F, -1.919862F, 0F);
      Tail3 = new ModelRenderer(this, 46, 6);
      Tail3.addBox(-0.5F, -1F, -0.5F, 1, 2, 6);
      Tail3.setRotationPoint(6F, -9F, 13F);
      Tail3.setTextureSize(64, 128);
      Tail3.mirror = true;
      setRotation(Tail3, 2.565634F, -1.919862F, 0F);
      RightFoot = new ModelRenderer(this, 0, 0);
      RightFoot.addBox(-1F, 0F, 0F, 2, 4, 1);
      RightFoot.setRotationPoint(-2F, 11F, 2F);
      RightFoot.setTextureSize(64, 128);
      RightFoot.mirror = true;
      setRotation(RightFoot, 0F, 0F, 0F);
      LeftFoot = new ModelRenderer(this, 0, 0);
      LeftFoot.addBox(-1F, 0F, 0F, 2, 4, 1);
      LeftFoot.setRotationPoint(2F, 11F, 2F);
      LeftFoot.setTextureSize(64, 128);
      LeftFoot.mirror = true;
      setRotation(LeftFoot, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Head.render(f5);
    Nose.render(f5);
    LeftEar.render(f5);
    RightEar.render(f5);
    Body.render(f5);
    Butt.render(f5);
    Neck.render(f5);
    RightLeg.render(f5);
    LeftLeg.render(f5);
    RightArm.render(f5);
    LeftArm.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Tail3.render(f5);
    RightFoot.render(f5);
    LeftFoot.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
