// Date: 19/08/2014 10:11:26
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.fandomcraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class modelKingdomKey extends ModelBase
{
  //fields
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape19;
    ModelRenderer Shape13;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape14;
    ModelRenderer Shape22;
    ModelRenderer Shape35;
    ModelRenderer Shape15;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape16;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape33;
    ModelRenderer Shape29;
    ModelRenderer Shape30;
    ModelRenderer Shape31;
    ModelRenderer Shape32;
    ModelRenderer Shape17;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape18;
  
  public modelKingdomKey()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape11 = new ModelRenderer(this, 14, 0);
      Shape11.addBox(-6F, 0F, 0F, 15, 3, 3);
      Shape11.setRotationPoint(0F, 12.5F, 0F);
      Shape11.setTextureSize(128, 64);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 0, 6);
      Shape12.addBox(0F, 0F, 0F, 6, 3, 3);
      Shape12.setRotationPoint(2.4F, 14.2F, 0F);
      Shape12.setTextureSize(128, 64);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, -0.2443461F);
      Shape19 = new ModelRenderer(this, 0, 6);
      Shape19.addBox(0F, 0F, 0F, 6, 3, 3);
      Shape19.setRotationPoint(-5.2F, 12.7F, 0F);
      Shape19.setTextureSize(128, 64);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0.2443461F);
      Shape13 = new ModelRenderer(this, 0, 12);
      Shape13.addBox(0F, 0F, 0F, 4, 4, 3);
      Shape13.setRotationPoint(-7F, 11F, 0F);
      Shape13.setTextureSize(128, 64);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0.7853982F);
      Shape20 = new ModelRenderer(this, 0, 12);
      Shape20.addBox(0F, 0F, 0F, 4, 4, 3);
      Shape20.setRotationPoint(10F, 11F, 0F);
      Shape20.setTextureSize(128, 64);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0.7853982F);
      Shape21 = new ModelRenderer(this, 12, 35);
      Shape21.addBox(0F, 0F, 0F, 3, 16, 3);
      Shape21.setRotationPoint(-7.5F, -3F, 0F);
      Shape21.setTextureSize(128, 64);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0.0698132F);
      Shape14 = new ModelRenderer(this, 12, 35);
      Shape14.addBox(0F, 0F, 0F, 3, 16, 3);
      Shape14.setRotationPoint(7.5F, -2.7F, 0F);
      Shape14.setTextureSize(128, 64);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, -0.0698132F);
      Shape22 = new ModelRenderer(this, 0, 19);
      Shape22.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape22.setRotationPoint(-7F, 13F, -0.5F);
      Shape22.setTextureSize(128, 64);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0.7853982F);
      Shape13 = new ModelRenderer(this, 0, 19);
      Shape13.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape13.setRotationPoint(10F, 13F, -0.5F);
      Shape13.setTextureSize(128, 64);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0.7853982F);
      Shape15 = new ModelRenderer(this, 0, 25);
      Shape15.addBox(0F, 0F, 0F, 4, 4, 4);
      Shape15.setRotationPoint(-0.5F, -7F, -0.5F);
      Shape15.setTextureSize(128, 64);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 18, 6);
      Shape23.addBox(0F, 0F, 0F, 8, 2, 3);
      Shape23.setRotationPoint(-7F, -2.7F, 0F);
      Shape23.setTextureSize(128, 64);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, -0.4363323F);
      Shape24 = new ModelRenderer(this, 18, 6);
      Shape24.addBox(0F, 0F, 0F, 8, 2, 3);
      Shape24.setRotationPoint(-6.8F, -2.5F, 0F);
      Shape24.setTextureSize(128, 64);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, -0.5934119F);
      Shape25 = new ModelRenderer(this, 18, 6);
      Shape25.addBox(-8F, 0F, 0F, 8, 2, 3);
      Shape25.setRotationPoint(10F, -2.7F, 0F);
      Shape25.setTextureSize(128, 64);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0.4363323F);
      Shape16 = new ModelRenderer(this, 18, 6);
      Shape16.addBox(-8F, 0F, 0F, 8, 2, 3);
      Shape16.setRotationPoint(9.8F, -2.5F, 0F);
      Shape16.setTextureSize(128, 64);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0.5934119F);
      Shape26 = new ModelRenderer(this, 50, 0);
      Shape26.addBox(0F, 0F, 0F, 4, 60, 4);
      Shape26.setRotationPoint(-0.5F, -70F, -0.5F);
      Shape26.setTextureSize(128, 64);
      Shape26.mirror = true;
      setRotation(Shape26, 0F, 0F, 0F);
      Shape27 = new ModelRenderer(this, 18, 11);
      Shape27.addBox(0F, 0F, 0F, 12, 3, 3);
      Shape27.setRotationPoint(2F, -70F, 0F);
      Shape27.setTextureSize(128, 64);
      Shape27.mirror = true;
      setRotation(Shape27, 0F, 0F, 0.1919862F);
      Shape33 = new ModelRenderer(this, 18, 11);
      Shape33.addBox(0F, -3F, 0F, 12, 3, 3);
      Shape33.setRotationPoint(2F, -50F, 0F);
      Shape33.setTextureSize(128, 64);
      Shape33.mirror = true;
      setRotation(Shape33, 0F, 0F, -0.1919862F);
      Shape29 = new ModelRenderer(this, 30, 33);
      Shape29.addBox(0F, -7F, 0F, 7, 7, 3);
      Shape29.setRotationPoint(0F, -56F, 0F);
      Shape29.setTextureSize(128, 64);
      Shape29.mirror = true;
      setRotation(Shape29, 0F, 0F, 0.6108652F);
      Shape30 = new ModelRenderer(this, 32, 17);
      Shape30.addBox(0F, 0F, 0F, 2, 2, 3);
      Shape30.setRotationPoint(10F, -59F, 0F);
      Shape30.setTextureSize(128, 64);
      Shape30.mirror = true;
      setRotation(Shape30, 0F, 0F, 0.7853982F);
      Shape31 = new ModelRenderer(this, 66, 41);
      Shape31.addBox(0F, 0F, 0F, 4, 18, 3);
      Shape31.setRotationPoint(3F, -69F, 0F);
      Shape31.setTextureSize(128, 64);
      Shape31.mirror = true;
      setRotation(Shape31, 0F, 0F, 0F);
      Shape32 = new ModelRenderer(this, 32, 17);
      Shape32.addBox(0F, 0F, 0F, 2, 2, 3);
      Shape32.setRotationPoint(10F, -64F, 0F);
      Shape32.setTextureSize(128, 64);
      Shape32.mirror = true;
      setRotation(Shape32, 0F, 0F, 0.7853982F);
      Shape17 = new ModelRenderer(this, 30, 34);
      Shape17.addBox(0F, 0F, 0F, 6, 6, 3);
      Shape17.setRotationPoint(6F, -67F, 0F);
      Shape17.setTextureSize(128, 64);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0.9599311F);
      Shape1 = new ModelRenderer(this, 0, 33);
      Shape1.addBox(0F, 0F, 0F, 3, 28, 3);
      Shape1.setRotationPoint(0F, -10F, 0F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 20, 54);
      Shape2.addBox(-1F, 0F, -1F, 5, 5, 5);
      Shape2.setRotationPoint(0F, 12.2F, 0F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 0, 3, 3);
      Shape3.setRotationPoint(1F, 17.5F, 1.5F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, -0.3665191F, 1.570796F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 0, 3, 3);
      Shape4.setRotationPoint(5F, 19F, 1.5F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, -1.27409F, 1.570796F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 0, 3, 3);
      Shape5.setRotationPoint(7F, 19F, 1.5F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, -1.064651F, 1.570796F, 0F);
      Shape6 = new ModelRenderer(this, 0, 0);
      Shape6.addBox(0F, 0F, 0F, 0, 3, 3);
      Shape6.setRotationPoint(8.5F, 19F, 1.5F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, -0.4537856F, 1.570796F, 0F);
      Shape7 = new ModelRenderer(this, 0, 0);
      Shape7.addBox(0F, 0F, 0F, 0, 3, 3);
      Shape7.setRotationPoint(9.5F, 22F, 1.5F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, -0.2094395F, 1.570796F, 0F);
      Shape8 = new ModelRenderer(this, 18, 17);
      Shape8.addBox(0F, 0F, 0F, 1, 3, 3);
      Shape8.setRotationPoint(10F, 26F, 2F);
      Shape8.setTextureSize(128, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0.5061455F, 1.570796F, 0F);
      Shape9 = new ModelRenderer(this, 6, 0);
      Shape9.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape9.setRotationPoint(14F, 26F, 2F);
      Shape9.setTextureSize(128, 64);
      Shape9.mirror = true;
      setRotation(Shape9, -0.2268928F, 1.570796F, 0F);
      Shape10 = new ModelRenderer(this, 6, 0);
      Shape10.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape10.setRotationPoint(10.5F, 28F, 2F);
      Shape10.setTextureSize(128, 64);
      Shape10.mirror = true;
      setRotation(Shape10, -0.2268928F, 1.570796F, 0F);
      Shape18 = new ModelRenderer(this, 14, 12);
      Shape18.addBox(0F, 0F, 0F, 0, 3, 2);
      Shape18.setRotationPoint(1.5F, 16.5F, 0.5F);
      Shape18.setTextureSize(128, 64);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape19.render(f5);
    Shape13.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape14.render(f5);
    Shape22.render(f5);
    Shape13.render(f5);
    Shape15.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape16.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
    Shape33.render(f5);
    Shape29.render(f5);
    Shape30.render(f5);
    Shape31.render(f5);
    Shape32.render(f5);
    Shape17.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape18.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
